#! /bin/bash

set -x

if [ "$#" -ne 8 ]; then
    echo "Usage: $0 <INPUT_ENDPOINT> <OUTPUT_ENDPOINT> <NEW_INT> <SIGNATURE_NAME> <SIGNATURE_BODY> <FINDTIME> <MAXRETRY> <BANTIME>"
    echo "Example: $0 10.0.0.1:502 10.0.1.1:502 eth1 modbus-invalidreg 'alert tcp $HOME_NET 502 -> $EXTERNAL_NET any (msg: \"Traffic detected\"; sid:1000001; rev:1; byte_test:1,=,0x02,8;)' 10m 5 1h"
    exit 1
fi

INPUT_ENDPOINT="$1"  #10.0.0.1:502
OUTPUT_ENDPOINT="$2" #10.0.1.1:502
NEW_INT="$3"         #eth1
SIGNATURE_NAME="$4"  #modbus-invalidreg
SIGNATURE_BODY="$5"  #alert tcp $HOME_NET 502 -> $EXTERNAL_NET any (msg: "Traffic detected"; sid:1000001; rev:1; byte_test:1,=,0x02,8;)
FINDTIME="$6"        #10m
MAXRETRY="$7"        #5
BANTIME="$8"         #1h

INPUT_ADDR="$(echo ${INPUT_ENDPOINT} | cut -d: -f1)"
INPUT_PORT="$(echo ${INPUT_ENDPOINT} | cut -d: -f2)"
OUTPUT_ADDR="$(echo ${OUTPUT_ENDPOINT} | cut -d: -f1)"
OUTPUT_PORT="$(echo ${OUTPUT_ENDPOINT} | cut -d: -f2)"

# add proxy

sed -i '/stream {/a \
    server {\
        listen '"${INPUT_ENDPOINT}"'; \
        proxy_pass '"${OUTPUT_ENDPOINT}"'; \
    }' /etc/nginx/nginx.conf
nginx -t
service nginx stop
service nginx start

# add interface
#/root/.asdf/shims/yq eval ".af-packet += [{\"interface\": \"${NEW_INT}\", \"cluster-id\": 98}]" -i /etc/suricata/suricata.yaml

# add address
INTERFACES=()
INTERFACES+=("${INPUT_ADDR}")
INTERFACES_LIST=$(tolist -o ${INTERFACES[@]})
/root/.asdf/shims/yq -i ".vars.\"address-groups\".HOME_NET = \"${INTERFACES_LIST}\"" /etc/suricata/suricata.yaml
suricata-update

# Create signature
tee /var/lib/suricata/rules/${SIGNATURE_NAME}.rules >/dev/null <<__EOF__
${SIGNATURE_BODY}
__EOF__
/root/.asdf/shims/yq eval '.["rule-files"] += ["'"${SIGNATURE_NAME}.rules"'"]' -i /etc/suricata/suricata.yaml
suricata -T -c /etc/suricata/suricata.yaml -v # test config
#suricatasc -c reload-rules

SID=$(echo ${SIGNATURE_BODY} | grep -Po 'sid:\K\d+')

# create
tee /etc/fail2ban/jail.d/suricata-${SID}.local >/dev/null <<__EOF__
[suricata-${SID}]
enabled  = true
filter   = suricata-${SID}
logpath  = /var/log/suricata/eve.json
backend  = polling
polltime = 0.1

findtime = ${FINDTIME}
maxretry = ${MAXRETRY}
bantime  = ${BANTIME}
action = %(action_)s
         loki
__EOF__

service fail2ban stop
service fail2ban start
