version: '3'
services:
  collector:
    build: ./collector
    image: icr/collector
    ports:
      - 1337:1337
    profiles:
      - collector
  collector-db:
    build: ./collector/db
    image: icr/collector-db
    ports:
      - 7331:7331
    profiles:
      - collector
  kathara-base:
    build: ./kathara-base
    image: icr/kathara-base
    profiles:
      - kathara
  mitm-arp-spoofing:
    build: ./mitm/arp-spoofing
    image: icr/mitm-arp-spoofing
    cap_add:
      - NET_ADMIN
    profiles:
      - kali
  dos-icmp-flood:
    build: ./dos/icmp-flood
    image: icr/dos-icmp-flood
    cap_add:
      - NET_ADMIN
    profiles:
      - kali
  Reconnaissance-arp-scanning:
    build: ./Reconnaissance/arp-scanning
    image: icr/reconnaissance-arp-scanning
    cap_add:
      - NET_ADMIN
    profiles:
      - kali
  dos-modbustcp-flood:
    build: ./dos/modbustcp-flood
    image: icr/dos-modbustcp-flood
    cap_add:
      - NET_ADMIN
    profiles:
      - kali
  apg:
    build: ./apg
    image: icr/apg
  conveyor:
    build: ./conveyor
    image: icr/conveyor
  laser:
    build: ./laser
    image: icr/laser
  plc:
    build: ./plc
    image: icr/plc
  rejector:
    build: ./rejector
    image: icr/rejector
  scada:
    build: ./scada
    image: icr/scada
